# Generated by Django 5.1.2 on 2024-11-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0005_facture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
