# Generated by Django 5.1.2 on 2024-11-19 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0006_delete_facture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reclamation',
        ),
    ]
