# Generated by Django 5.1.2 on 2024-11-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0006_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportinite',
            name='commercial',
            field=models.CharField(choices=[('Colonel Nizar', 'Colonel Nizar'), ('Ikram', 'Adm/Chef Ikram'), ('Cne Radhouen', 'Cne Radhouen'), ('Lt Sofienne', 'Lt Sofienne'), ('Adj/C Brahim', 'Adj/C Brahim'), ('Adj/M Chabchoub', 'Adj/M Chabchoub'), ('Chef Imed', 'Sgt/C Imed')], max_length=20),
        ),
    ]
