# Generated by Django 5.1.2 on 2024-11-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0007_alter_opportinite_commercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportinite',
            name='client',
        ),
        migrations.RemoveField(
            model_name='opportinite',
            name='commercial',
        ),
    ]
